name: linux
on:
  push:
    branches:
      - 'issue62047'
    paths:
      - '0001-cmd-remove-support-for-GOROOT_FINAL.patch'
      - '.github/workflows/linux.yml'

jobs:

  build:
    strategy:
      matrix:
        go_arch: [amd64, arm64, ppc64le]
      fail-fast: false
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.x
      id: go

    - name: Get patch files
      uses: actions/checkout@v3

    - name: Build go from tip
      uses: iwdgo/gotip-build@issue62047
      id: gotip
      with:
        go_variables: GOOS=linux GOARCH=${{ matrix.go_arch }} GO_TEST_SHORT=0 GO_TEST_TIMEOUT_SCALE=5
        test_build: true

    - name: Upload go executable
      uses: actions/upload-artifact@v3
      if: ${{ env.crosscompile == 'false' }}
      with:
        name: gotip-${{ env.goos }}-${{ env.goarch }}
        path: go/bin/

    - name: Upload go executable
      uses: actions/upload-artifact@v3
      if: ${{ env.crosscompile == 'true' }}
      with:
        name: gotip-${{ env.goos }}-${{ env.goarch }}
        path: go/bin/${{ env.goos }}_${{ env.goarch }}
